name: CMake Build Workflow

on:
  push:
    branches: [ ] # Temporarily disabled
  pull_request:
    branches: [ ] # Temporarily disabled

env:
  BUILD_TYPE: Release
  BUILD_TESTS: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  VCPKG_BUILTIN_BASELINE: c8696863d371ab7f46e213d8f5ca923c4aef2a00
  VCPKG_ENABLE_METRICS: 1
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/vcpkg/bincache
  VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'
  OUTPUT_DIRECTORY: out/build

permissions:
  actions: read
  deployments: write
  contents: write
  id-token: write
  security-events: write

jobs:
  build_project:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ] # , ubuntu-latest, macos-latest

    steps:
      - name: Checkout & Init Submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest

      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{env.VCPKG_ROOT}}
          vcpkgGitCommitId: ${{env.VCPKG_BUILTIN_BASELINE}}
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Inspect Root Directory
        if: matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}
        run: ls

      - name: Configure and Build Project
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
          configurePreset: ${{env.BUILD_TYPE}}
          buildPreset: ${{env.BUILD_TYPE}}

      - name: Run Tests
        working-directory: ${{github.workspace}}/${{env.OUTPUT_DIRECTORY}}/${{env.BUILD_TYPE}}
        run: ctest -C ${{env.BUILD_TYPE}} --repeat until-pass:8 --output-on-failure --verbose

      - name: Run Benchmark
        working-directory: ${{github.workspace}}/${{env.OUTPUT_DIRECTORY}}/${{env.BUILD_TYPE}}/bin
        run: ./SubmodulesBenchmark.exe
