name: cpp-submodules CMake Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  BUILD_TESTS: true
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  VCPKG_BUILTIN_BASELINE: 5a38b5ec0eee3d1a1a6faab5e944617fee2697cf
  VCPKG_ENABLE_METRICS: 1
  VCPKG_DEFAULT_TRIPLET: x64-windows-release
  VCPKG_DEFAULT_BINARY_CACHE: ${{github.workspace}}/vcpkg/bincache
  VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'
  OUTPUT_DIRECTORY: out/build

permissions:
  actions: read
  deployments: write
  contents: write
  id-token: write
  security-events: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout & Init Submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install Latest CMake Version
        uses: lukka/get-cmake@latest

      - name: Setup VCPKG
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{env.VCPKG_ROOT}}
          vcpkgGitCommitId: ${{env.VCPKG_BUILTIN_BASELINE}}
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Configure and Build Project
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
          configurePreset: ${{env.BUILD_TYPE}}
          buildPreset: ${{env.BUILD_TYPE}}

      - name: Run Tests
        working-directory: ${{github.workspace}}/${{env.OUTPUT_DIRECTORY}}/${{env.BUILD_TYPE}}
        run: ctest -C ${{env.BUILD_TYPE}} --repeat until-pass:8 --output-on-failure --verbose

      - name: Run Submodules Benchmark
        working-directory: ${{github.workspace}}/${{env.OUTPUT_DIRECTORY}}/${{env.BUILD_TYPE}}/bin
        run: ./SubmodulesBenchmark.exe --benchmark_format=json | tee submodules_benchmark_result.json

      - name: Push Submodules Benchmark Result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'googlecpp'
          output-file-path: ${{github.workspace}}/${{env.OUTPUT_DIRECTORY}}/${{env.BUILD_TYPE}}/bin/submodules_benchmark_result.json
          github-token: ${{ secrets.LUCOISO_PAT }}
          auto-push: true
          gh-repository: 'github.com/lucoiso/cpp-submodules'